version: '3'

services:
  nginx:
    image: mohsinamin/minifacebookstack
    restart: unless-stopped
    ports:
      - 80:80
    depends_on:
      - userservice
      - statusservice
      - storyservice

  userservice:
    image: mohsinamin/userservice
    restart: unless-stopped
    depends_on:
      - userdb

  userdb:
    image: mysql:latest
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'miniuser'
      MYSQL_USER: 'minifacebook'
      MYSQL_PASSWORD: 'PuxBnWhh89HxDbZN'
    volumes:
      - ./api/userdb:/docker-entrypoint-initdb.d
      - userdata:/var/lib/mysql

  statusservice:
    image: mohsinamin/statusservice
    restart: unless-stopped
    depends_on:
      - statusdb

  statusdb:
    image: mysql:latest
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ministatus'
      MYSQL_USER: 'minifacebook'
      MYSQL_PASSWORD: 'PuxBnWhh89HxDbZN'
    volumes:
      - ./api/statusdb:/docker-entrypoint-initdb.d
      - statusdata:/var/lib/mysql

  storyservice:
    image: mohsinamin/storyservice
    restart: unless-stopped
    depends_on:
      - storydb
      - storyobjectdb

  storydb:
    image: mysql:latest
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ministory'
      MYSQL_USER: 'minifacebook'
      MYSQL_PASSWORD: 'PuxBnWhh89HxDbZN'
    volumes:
      - ./api/storydb:/docker-entrypoint-initdb.d
      - storydata:/var/lib/mysql

  storyobjectdb:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=2yScPd5Ss5BGuEUk
      - MINIO_ROOT_PASSWORD=mOLBN9GwA75veIWlmYU0mhlTTWeUkqyg
    command: server --address 0.0.0.0:9000 /data
    volumes:
      - storyobjectdata:/data

volumes:
  userdata:
  statusdata:
  storydata:
  storyobjectdata:
