version: '3'

services:
  nginx:
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - userservice
      - statusservice
      - storyservice

  userservice:
    build: ./user
    restart: unless-stopped
    depends_on:
      - userdb

  userdb:
    image: mysql:latest
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'miniuser'
      MYSQL_USER: 'minifacebook'
      MYSQL_PASSWORD: 'PuxBnWhh89HxDbZN'
    volumes:
      - ./userdb:/docker-entrypoint-initdb.d
      - userdata:/var/lib/mysql

  statusservice:
    build: ./status
    restart: unless-stopped
    depends_on:
      - statusdb

  statusdb:
    image: mysql:latest
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ministatus'
      MYSQL_USER: 'minifacebook'
      MYSQL_PASSWORD: 'PuxBnWhh89HxDbZN'
    volumes:
      - ./statusdb:/docker-entrypoint-initdb.d
      - statusdata:/var/lib/mysql

  storyservice:
    build: ./story
    restart: unless-stopped
    depends_on:
      - storydb
      - storyobjectdb

  storydb:
    image: mysql:latest
    restart: unless-stopped
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'ministory'
      MYSQL_USER: 'minifacebook'
      MYSQL_PASSWORD: 'PuxBnWhh89HxDbZN'
    volumes:
      - ./storydb:/docker-entrypoint-initdb.d
      - storydata:/var/lib/mysql

  storyobjectdb:
    image: minio/minio:latest
    environment:
      - MINIO_ROOT_USER=2yScPd5Ss5BGuEUk
      - MINIO_ROOT_PASSWORD=mOLBN9GwA75veIWlmYU0mhlTTWeUkqyg
    command: server --address 0.0.0.0:9000 /data
    volumes:
      - storyobjectdata:/data

volumes:
  userdata:
  statusdata:
  storydata:
  storyobjectdata: